name: linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1.1.0
      - name: Check Translation files
        run: |
          echo "::group::French"
          python3 ${GITHUB_WORKSPACE}/.tools/update_translation.py fr
          echo "::endgroup::"
          echo "::group::Deutch"
          python3 ${GITHUB_WORKSPACE}/.tools/update_translation.py de
          echo "::endgroup::"
          echo "::group::Spanish"
          python3 ${GITHUB_WORKSPACE}/.tools/update_translation.py es
          echo "::endgroup::"
          echo "::group::Rusian"
          python3 ${GITHUB_WORKSPACE}/.tools/update_translation.py ru
          echo "::endgroup::"
      #- name: Install V8
      #  run: sudo apt-get install -y libv8-dev
      #- name: Validate CITATION.cff
      #  uses: dieghernan/cff-validator@main
